version: "3"

services:
  app:
    image: my-app:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1  
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
